### ISSUE TITLE
Zone move notice

### ISSUE THREAD

**Issue by chrisvel** [scoop/autotask_api#11]
I saw an email those days about a transition 

> "America West (ww5.autotask.net) to America West 2 (ww15.autotask.net)". 

Do you think it's going to impact us ?

It also says: 

>  If you are using our custom API, be sure to modify all of your APIs so that they are using getZoneInfo() instead of zone-specific URLs.  Please check any third party vendor information or contact them directly prior to this change to be sure they are using getZoneInfo().

The change week is April 11th, so regarding their (unprofessionally) very short notice, I am starting to feel anxious.

**Comment by trepidity** [comment]
I always call getZoneInfo and the use the service URL returned. It's the only safe way.

**Comment by scoop** [comment]
Yeah, I agree. If you follow the example in the README there's nothing you need to change for this announced zone move.

**Comment by chrisvel** [comment]
I am afraid I have it hardcoded as a const in the application. If I understand what you say is that by using getZoneInfo() you always get the current endpoint ?

**Comment by scoop** [comment]
@chrisvel Yes, see the example in the README. https://github.com/scoop/autotask_api#webservices-endpoints

**Comment by chrisvel** [comment]
@scoop thank you
