### ISSUE TITLE
Can you provide an Example of a query with multiple conditions ? 

### ISSUE THREAD

**Issue by ajmyers01** [scoop/autotask_api#12]
I'm trying to use this gem to write queries with multiple conditions. I was wondering if there was an example you could provide as I have not been able to get it to work yet, from the information in the README

**Comment by scoop** [comment]
Alex,

to apply multiple conditions you basically need to construct a query by hand without a condition and then use the returned object to add whatever conditions you need.

For example:

```ruby
@client = AutotaskAPI::Client.new do |client|
  # ..
end

@query = AutotaskAPI::QueryXML.new do |query|
  query.entity = 'AccountTodo'
end
@query.add_condition 'AssignedToResourceID', 'Equals', @user_id
@query.add_condition 'CreateDateTime', 'GreaterThan', 3.months.ago.to_s
```

You can then apply that query like so:

```ruby
@client.entities_for(@query).each do |todo|
  # ..
end
```

Hope this helps.

-Patrick

**Comment by ajmyers01** [comment]
That worked perfectly! Thanks @scoop
