### ISSUE TITLE
Is there a payload limit for requesting from the autotask api ? 

### ISSUE THREAD

**Issue by ajmyers01** [scoop/autotask_api#13]
I'm trying to pull back all active accounts and seem to be only getting A-B and none of the other records. Is the response paginated / how can I handle this.

**Comment by scoop** [comment]
Alex,

unfortunately, the concept of pagination is completely alien to the Autotask API, hence the lack of support in my Ruby wrapper.

The docs say this about the `query()` method:

> The Web Service API query() call will return a maximum of 500 objects per call, sorted by the id field. If you would like to retrieve more than 500 items, you should resubmit your query with a condition on the id field.

.. which is quite a bummer to be frank. So basically, you send a query, make a note of the last `id` you get returned and re-submit your query with a condition of `id > @last_id`.

Hope this helps.

-Patrick
