### ISSUE TITLE
support a proxy

### ISSUE THREAD

**Issue by trepidity** [scoop/autotask_api#15]
Would it be possible to support a proxy with the client?
Additionally, pass in the parameter to ignore client certificates. `http.auth.ssl.verify_mode = :none`

The reason is that something broke with the Autotask API and now all these calls are broken and I need to be able to debug the actual SOAP call.

**Comment by trepidity** [comment]
Actually, after more digging around, it appears to be an issue with Savon. It's sending the authorization header when trying to get the WSDL and AutoTask is rejecting this.

**Comment by scoop** [comment]
Jared,

can you share what exactly broke and where? It's a little vague to reproduce for me as-is.

For the proxy, something like this should already work:

```ruby
client = AutotaskAPI::Client.new do |c|
  # ..
  c.proxy = "http://proxy.domain.org:8080"
end
```

-Patrick

**Comment by trepidity** [comment]
Thanks for the response; yes that does route the traffic through the proxy. Not sure why it didn't work the first time I tried that. Sorry for the bother. I'm going to open a second issue as the topic is different, but is why I was trying to make the proxy call.
