### ISSUE TITLE
undefined method `first_name' for nil:NilClass

### ISSUE THREAD

**Issue by trepidity** [scoop/autotask_api#18]
Kinda off topic, but what's the best way to handle this situation?
An example is that you make a call for "ServiceCall" and then later ticket and contact. In this case, for whatever reason, no contact was returned for the ticket and thus the following method call will throw an undefined method error.

`ticket.contact.first_name`

To some degree, it seems that the issue happens most when there are +2 queries to be made. For example, in the case of ServiceCall, to get the resource you have to query through `service_call_ticket` and `service_call_ticket_resource` to get `resource`, which if no resource is associated, then this method would fail ` service_call.service_call_ticket.service_call_ticket_resource.resource`

Is there a way to adjust this lookup so that the API doesn't throw an unknown method and instead would return something useful.

Sorry if this doesn't exactly make sense.

**Comment by scoop** [comment]
You can use `Object#try` like this:

```ruby
ticket.contact.try :first_name
```

This returns `nil` when `ticket.contact` is `nil`.

More at: https://apidock.com/rails/Object/try

**Comment by trepidity** [comment]
Ooooh thanks!
