### ISSUE TITLE
More fields in account entity?

### ISSUE THREAD

**Issue by abhishek-kant** [scoop/autotask_api#26]
We needed to use more fields in the account entity, and we added them by extending the account class in our app like this: 
`AutotaskAPI::Account.class_eval do
  self.fields = fields + %i[account_number phone alternate_phone1
                            alternate_phone2 fax bill_to_address1
                            bill_to_address2 bill_to_city
                            bill_to_zip_code bill_to_state]
end
`
How about I add these extra fields to the account class it self and create a PR?
So that others who need these fields don't have to this.

**Comment by scoop** [comment]
Just change the original file and submit a PR. Please make sure to follow the style I suggested in #25.
