### ISSUE TITLE
Client Entity shared across other classes

### ISSUE THREAD

**Issue by trepidity** [scoop/autotask_api#28]
I'm not even sure if this is correct, but it seems so.

I have a couple of different classes that do something like so.

```
class ZoneInfoService
        attr_accessor :client

        def initialize(args)
                self.client = AutotaskAPI::Client.new do |c|
                        c.endpoint = 'https://webservices2.autotask.net/ATServices/1.5/atws.asmx'
                end
        end
end
```

Somehow it seems that the `client` is being shared across the classes. I see this because the c.endpoint should be different between the different classes, but instead, it's the original value. Am I going looney?

**Comment by scoop** [comment]
On creation, the `Autotask::Client` class sets `AutotaskAPI::Entity.client` to itself in case the latter is empty. All other entity classes descend from that class.

Honestly, this API wrapper was never architected in a way that it could be used by multiple client instances simultaneously. 

Depending on the usage scenario might make be worth a try to explicitly set `AutotaskAPI::Entity.client` after initializing the client.

**Comment by trepidity** [comment]
So you are saying that it kinda acts like a Singleton?

**Comment by trepidity** [comment]
@scoop Are you still using this library today? Just wondering if I should make my own adjustments or refactor this library to support multiple clients.

**Comment by scoop** [comment]
I use it every day.

**Comment by trepidity** [comment]
I would be willing to submit a PR that refactors the client, but I know the quality will not be the same. Unless you are willing to work with me on it or do it yourself, I might work on my own version.

I'm open to suggestions.

**Comment by scoop** [comment]
I’ll happily lend a hand but I have a couple newborns in the house right now, which means available time can be spotty.
